In [ ]:
import pandas as pd

Primeiras linhas do dataset

In [ ]:
df = pd.read_csv("/social_media_vs_productivity.csv")
df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

Informações do dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  object
 2   job_type                        30000 non-null  object
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  object
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(3)
memory usage: 3.9+ MB

# Limpeza dos dados

In [ ]:
#seleção das colunas que vão ser utilizadas
colunas_utilizadas = [
    'age',
    'gender',
    'daily_social_media_time',
    'social_platform_preference',
    'stress_level',
    'sleep_hours',
    'days_feeling_burnout_per_month',

]

df_limpo = df[colunas_utilizadas].copy()
df_limpo.head()

,age,gender,daily_social_media_time,social_platform_preference,stress_level,sleep_hours,days_feeling_burnout_per_month
0,56,Male,4.180940,Facebook,4.0,5.116546,11
1,46,Male,3.249603,Twitter,7.0,5.103897,25
2,32,Male,NaN,Twitter,4.0,8.583222,17
3,60,Female,NaN,Facebook,6.0,6.052984,4
4,25,Male,NaN,Telegram,7.0,5.405706,30

Coluna 'age'

In [ ]:
#contagem de nulos na coluna 'age'
print(f"Número de valores nulos: {df_limpo['age'].isnull().sum()}")

Número de valores nulos: 0

In [ ]:
#remove os nulos na coluna 'age'
df_limpo = df_limpo.dropna(subset=['age'])

print(f"Número de valores nulos após limpeza: {df_limpo['age'].isnull().sum()}")

Número de valores nulos após limpeza: 0

Coluna 'gender'

In [ ]:
#valores únicos da coluna 'gender'
df_limpo['gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [ ]:
#contagem de nulos na coluna 'gender'
print(f"Número de valores nulos: {df_limpo['gender'].isnull().sum()}")

Número de valores nulos: 0

Coluna 'daily_social_media_time'

In [ ]:
#contagem de nulos na coluna 'daily_social_media_time'
print(f"Número de valores nulos: {df_limpo['daily_social_media_time'].isnull().sum()}")

Número de valores nulos: 2765

In [ ]:
#substituir os nulos pela mediana
mediana = df_limpo['daily_social_media_time'].median()

df_limpo['daily_social_media_time'] = df_limpo['daily_social_media_time'].fillna(mediana)

In [ ]:
#contagem de nulos na coluna 'daily_social_media_time' (após limpeza)
print(f"Número de valores nulos: {df_limpo['daily_social_media_time'].isnull().sum()}")

Número de valores nulos: 0

In [ ]:
#tipo de valores da coluna daily_social_media_time
print(f"Tipo de dado: {df_limpo['daily_social_media_time'].dtype}")

Tipo de dado: float64

In [ ]:
#verificar se os valores estão faixa de 0 a 24
df_limpo['daily_social_media_time'].describe()

count    30000.000000
mean         3.105353
std          1.977046
min          0.000000
25%          1.797748
50%          3.025913
75%          4.219533
max         17.973256
Name: daily_social_media_time, dtype: float64

In [ ]:
#arredondar as horas para duas casas decimais
df_limpo['daily_social_media_time'] = df_limpo['daily_social_media_time'].round(2)

df_limpo['daily_social_media_time'].head()

0    4.18
1    3.25
2    3.03
3    3.03
4    3.03
Name: daily_social_media_time, dtype: float64

Coluna 'social_platform_preference'

In [ ]:
#valores únicos da coluna 'social_platform_preference'
df_limpo['social_platform_preference'].unique()

array(['Facebook', 'Twitter', 'Telegram', 'TikTok', 'Instagram'],
      dtype=object)

In [ ]:
#contagem de nulos
print(f"Número de valores nulos: {df_limpo['social_platform_preference'].isnull().sum()}")

Número de valores nulos: 0

Coluna 'strees_level'

In [ ]:
#valores únicos da coluna 'stress_level'
df_limpo['stress_level'].unique()

array([ 4.,  7.,  6.,  5.,  3.,  9., nan, 10.,  1.,  2.,  8.])

In [ ]:
#contagem dos nulos da coluna 'stress_level'
print(f"Número de valores nulos: {df_limpo['stress_level'].isnull().sum()}")

Número de valores nulos: 1904

In [ ]:
#limpeza dos nulos da coluna 'stress_level'
df_limpo = df_limpo.dropna(subset=['stress_level'])

In [ ]:
#contagem dos nulos da coluna 'stress_level' (após limpeza)
print(f"Número de valores nulos: {df_limpo['stress_level'].isnull().sum()}")

Número de valores nulos: 0

Coluna 'sleep_hours'

In [ ]:
#contagem dos nulos da coluna 'sleep_hours'
print(f"Número de valores nulos: {df_limpo['sleep_hours'].isnull().sum()}")

Número de valores nulos: 2434

In [ ]:
#substituir os nulos pela mediana
mediana = df_limpo['sleep_hours'].median()

df_limpo['sleep_hours'] = df_limpo['sleep_hours'].fillna(mediana)

In [ ]:
#contagem de nulos na coluna 'sleep_hours' (após limpeza)
print(f"Número de valores nulos: {df_limpo['sleep_hours'].isnull().sum()}")

Número de valores nulos: 0

In [ ]:
#tipo de valores da coluna 'sleep_hours'
print(f"Tipo de dados: {df_limpo['sleep_hours'].dtype}")

Tipo de dados: float64

In [ ]:
#verificar se os valores estão faixa de 0 a 24
df_limpo['sleep_hours'].describe()

count    28096.000000
mean         6.498682
std          1.400596
min          3.000000
25%          5.594455
50%          6.495450
75%          7.396246
max         10.000000
Name: sleep_hours, dtype: float64

In [ ]:
#arredondar as horas para duas casas decimais
df_limpo['sleep_hours'] = df_limpo['sleep_hours'].round(2)

df_limpo['sleep_hours'].head()

0    5.12
1    5.10
2    8.58
3    6.05
4    5.41
Name: sleep_hours, dtype: float64

Coluna 'days_feeling_burnout_per_mount'

In [ ]:
#contagem dos nulos da coluna 'days_feeling_burnout_per_month'
print(f"Número de valores nulos: {df_limpo['days_feeling_burnout_per_month'].isnull().sum()}")

Número de valores nulos: 0

In [ ]:
#checar se há valores menores que 0 ou maiores que 31
df_limpo['days_feeling_burnout_per_month'].describe()

count    28096.000000
mean        15.579869
std          9.251998
min          0.000000
25%          8.000000
50%         16.000000
75%         24.000000
max         31.000000
Name: days_feeling_burnout_per_month, dtype: float64

#Checagem após limpeza

In [ ]:
df_limpo.shape

(28096, 7)

In [ ]:
df_limpo.head()

,age,gender,daily_social_media_time,social_platform_preference,stress_level,sleep_hours,days_feeling_burnout_per_month
0,56,Male,4.18,Facebook,4.0,5.12,11
1,46,Male,3.25,Twitter,7.0,5.10,25
2,32,Male,3.03,Twitter,4.0,8.58,17
3,60,Female,3.03,Facebook,6.0,6.05,4
4,25,Male,3.03,Telegram,7.0,5.41,30

In [ ]:
df_limpo.isnull().sum()

age                               0
gender                            0
daily_social_media_time           0
social_platform_preference        0
stress_level                      0
sleep_hours                       0
days_feeling_burnout_per_month    0
dtype: int64

#Salvar novo dataset

In [ ]:
df_limpo.to_csv('dataset_limpo.csv', index=False)